apiVersion: v1
kind: Service
metadata:
  name: springboot-app-7b597d5547-xgcxr 
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: springboot-app-7b597d5547-xgcxr 
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000
